name: Run app and update post dates

on:
  push:
    branches:
      - main  # Run this workflow on pushes to the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you are using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure requirements.txt includes necessary packages

    - name: Run app.py
      run: python app.py
      
    - name: Run week.py
      run: python week.py
